version: "2.1"
services:
  bundesliga:
    image: lukasdotcom/bundesliga:development
    container_name: bundesliga
    links:
      - db
    environment:
      - NEXTAUTH_URL=http//localhost # The url of the server
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_DATABASE=bundesliga
      - MIN_UPDATE_TIME=120 # Minimum amount of seconds to pass before the data updates on Fri, Sat, and Sun to prevent spamming the api.
      - BUNDESLIGA_API= # How to get this value is in the README
      - DOMAIN=http://localhost # unless you are not using localhost to access the website you do not have to change this
      # Get your oauth details for sign in with google and fill it in below
      - GOOGLE_ID=none
      - GOOGLE_SECRET=none
    ports:
      - 80:3000
    restart: always
    volumes:
      - /locationToWhereThisGithubIsDownloaded:/var/www/bundesliga
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bundesliga
    restart: always
    volumes:
      - bundesliga:/var/lib/mysql
volumes:
  bundesliga:
    external: true