version: "2.1"
services:
  bundesliga:
    image: lukasdotcom/bundesliga:latest # Change latest to nightly if you want to be using the bleeding edge
    container_name: bundesliga
    links:
      - db
    environment:
      - NEXTAUTH_URL=http//localhost # The url of the server
      - MYSQL_USER=bundesliga
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_DATABASE=bundesliga
      - MIN_UPDATE_TIME=120 # Minimum amount of seconds to pass before the data updates on Fri, Sat, and Sun to prevent spamming the api.
      - BUNDESLIGA_API= # How to get this value is in the README
      # Get your oauth 2.0 details for sign in with google and fill it in below
      - GOOGLE_ID=none
      - GOOGLE_SECRET=none
      - NEXTAUTH_SECRET= # run openssl rand -base64 32 and plug the result into this
      - BCRYPT_ROUNDS=9 # The number of rounds the password should be hashed
    ports:
      - 80:3000
    restart: always
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=bundesliga
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bundesliga
    restart: always
    volumes:
      - bundesliga:/var/lib/mysql
volumes:
  bundesliga:
    external: true